FROM node:20-alpine as build-step

WORKDIR /frontend

COPY ./frontend/package.json ./frontend/tsconfig.json ./frontend/yarn.lock ./
COPY ./frontend/src ./src
COPY ./frontend/public ./public

RUN yarn install

# 👇 Add this line
ENV HOST=0.0.0.0

CMD ["yarn", "start"]